# dir: /source
FROM node:22-alpine3.20

COPY "./WebApp" "/root/WebApp"
COPY "./#external/mirrorsharp/WebAssets/dist" "/root/#external/mirrorsharp/WebAssets/dist"
COPY "./#external/mirrorsharp-codemirror-6-preview/WebAssets/dist" "/root/#external/mirrorsharp-codemirror-6-preview/WebAssets/dist"

WORKDIR "/root/WebApp"
RUN rm "package-lock.json"
RUN npm install

EXPOSE 44200
ENTRYPOINT [ "npm", "run", "start" ]