# dir: /
FROM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y wget && apt-get clean -y

WORKDIR /root
RUN mkdir .dotnet

COPY "./source/WebApp.Server/const-generics.net9.0-linux-Release-x64.tar.gz" "/root"
RUN tar -zxvf "const-generics.net9.0-linux-Release-x64.tar.gz" -C ".dotnet" && \
    rm "const-generics.net9.0-linux-Release-x64.tar.gz"

COPY "./source/Container/bin/publish" "/root/Container"
WORKDIR /root/Container/
RUN rm -rf .env System.Reflection.Metadata.dll *.pdb xmldocs refs *.dbg
RUN cp /root/.dotnet/shared/Microsoft.NETCore.App/8.0.0/System.Reflection.Metadata.dll .


FROM ubuntu:22.04
COPY --from=builder /root /root
WORKDIR /root/Container

ENV DOTNET_ROOT="/root/.dotnet"
ENV PATH="$PATH:/root/.dotnet"

ENV DOTNET_ROLL_FORWARD=LatestMajor
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

ENTRYPOINT [ "dotnet", "/root/Container/SharpLab.Container.dll" ]