# dir: /
FROM ubuntu:22.04

RUN apt-get update && apt-get install wget -y && apt-get install libicu-dev -y && apt-get clean -y

WORKDIR /root
RUN wget "https://aka.ms/dotnet/10.0.1xx-preview2/daily/dotnet-sdk-linux-x64.tar.gz" -O "dotnet-sdk.tar.gz" && \
    mkdir -p .dotnet && \
    tar -zxvf "dotnet-sdk.tar.gz" -C ".dotnet" && \
    rm -rf "dotnet-sdk.tar.gz" .dotnet/sdk .dotnet/packs .dotnet/templates .dotnet/template-packs .dotnet/sdk-manifests .dotnet/library-packs

COPY "./source/Container/bin/publish" "/root/Container"

WORKDIR /root/Container

ENV DOTNET_ROOT="/root/.dotnet"
ENV PATH="$PATH:/root/.dotnet"

ENV DOTNET_ROLL_FORWARD=LatestMajor

ENTRYPOINT [ "dotnet", "/root/Container/SharpLab.Container.dll" ]